/**
 * Машиночитаемые коды ошибок API.
 * Backend всегда отвечает кодом из этого списка, frontend переводит код
 * в понятное пользователю сообщение (см. apps/web/src/i18n/locales/*).
 */
export const ErrorCode = {
  // Общие
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // Доступ и авторизация
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_INIT_DATA: 'INVALID_INIT_DATA',
  INIT_DATA_EXPIRED: 'INIT_DATA_EXPIRED',
  TELEGRAM_AUTH_NOT_CONFIGURED: 'TELEGRAM_AUTH_NOT_CONFIGURED',
  NO_MEMBERSHIP: 'NO_MEMBERSHIP',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  DEV_LOGIN_DISABLED: 'DEV_LOGIN_DISABLED',

  // Компания, филиалы, сотрудники
  COMPANY_NOT_FOUND: 'COMPANY_NOT_FOUND',
  BRANCH_NOT_FOUND: 'BRANCH_NOT_FOUND',
  BRANCH_ACCESS_DENIED: 'BRANCH_ACCESS_DENIED',
  DUPLICATE_BRANCH_NAME: 'DUPLICATE_BRANCH_NAME',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_MEMBER: 'USER_ALREADY_MEMBER',
  TELEGRAM_ID_TAKEN: 'TELEGRAM_ID_TAKEN',
  BRANCH_REQUIRED: 'BRANCH_REQUIRED',
  ROLE_ASSIGNMENT_FORBIDDEN: 'ROLE_ASSIGNMENT_FORBIDDEN',
  LAST_OWNER: 'LAST_OWNER',
  CANNOT_MODIFY_SELF: 'CANNOT_MODIFY_SELF',
  ALREADY_REGISTERED: 'ALREADY_REGISTERED',

  // Товары и склад
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  VARIANT_NOT_FOUND: 'VARIANT_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  BRAND_NOT_FOUND: 'BRAND_NOT_FOUND',
  BARCODE_NOT_FOUND: 'BARCODE_NOT_FOUND',
  DUPLICATE_SKU: 'DUPLICATE_SKU',
  DUPLICATE_BARCODE: 'DUPLICATE_BARCODE',
  DUPLICATE_CATEGORY: 'DUPLICATE_CATEGORY',
  DUPLICATE_BRAND: 'DUPLICATE_BRAND',
  CATEGORY_CYCLE: 'CATEGORY_CYCLE',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',

  // IMEI
  IMEI_NOT_FOUND: 'IMEI_NOT_FOUND',
  INVALID_IMEI: 'INVALID_IMEI',
  INVALID_SERIAL_NUMBER: 'INVALID_SERIAL_NUMBER',
  IMEI_ALREADY_SOLD: 'IMEI_ALREADY_SOLD',
  DUPLICATE_IMEI: 'DUPLICATE_IMEI',

  // Продажи и возвраты
  SALE_NOT_FOUND: 'SALE_NOT_FOUND',
  RETURN_LIMIT_EXCEEDED: 'RETURN_LIMIT_EXCEEDED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const ERROR_CODES: readonly ErrorCode[] = Object.values(ErrorCode);

export function isErrorCode(value: unknown): value is ErrorCode {
  return typeof value === 'string' && (ERROR_CODES as readonly string[]).includes(value);
}
